//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetFileDataSOAPService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VEArchive", Namespace="http://tempuri.org/")]
    public partial class VEArchive : object
    {
        
        private string base64DataField;
        
        private byte[] dataField;
        
        private string archiveDateField;
        
        private string messageField;
        
        private bool successField;
        
        private int archieveidField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string base64Data
        {
            get
            {
                return this.base64DataField;
            }
            set
            {
                this.base64DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string archiveDate
        {
            get
            {
                return this.archiveDateField;
            }
            set
            {
                this.archiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int archieveid
        {
            get
            {
                return this.archieveidField;
            }
            set
            {
                this.archieveidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VEDocument", Namespace="http://tempuri.org/")]
    public partial class VEDocument : object
    {
        
        private int lineNumberField;
        
        private string messageField;
        
        private byte[] dataField;
        
        private bool successField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int lineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetFileDataSOAPService.Service1Soap")]
    public interface Service1Soap
    {
        
        // CODEGEN: Generating message contract since element name filename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestArchive", ReplyAction="*")]
        GetFileDataSOAPService.GetLatestArchiveResponse GetLatestArchive(GetFileDataSOAPService.GetLatestArchiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestArchive", ReplyAction="*")]
        System.Threading.Tasks.Task<GetFileDataSOAPService.GetLatestArchiveResponse> GetLatestArchiveAsync(GetFileDataSOAPService.GetLatestArchiveRequest request);
        
        // CODEGEN: Generating message contract since element name filename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstArchive", ReplyAction="*")]
        GetFileDataSOAPService.GetFirstArchiveResponse GetFirstArchive(GetFileDataSOAPService.GetFirstArchiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFirstArchive", ReplyAction="*")]
        System.Threading.Tasks.Task<GetFileDataSOAPService.GetFirstArchiveResponse> GetFirstArchiveAsync(GetFileDataSOAPService.GetFirstArchiveRequest request);
        
        // CODEGEN: Generating message contract since element name filename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllArchive", ReplyAction="*")]
        GetFileDataSOAPService.GetAllArchiveResponse GetAllArchive(GetFileDataSOAPService.GetAllArchiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllArchive", ReplyAction="*")]
        System.Threading.Tasks.Task<GetFileDataSOAPService.GetAllArchiveResponse> GetAllArchiveAsync(GetFileDataSOAPService.GetAllArchiveRequest request);
        
        // CODEGEN: Generating message contract since element name filename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData", ReplyAction="*")]
        GetFileDataSOAPService.GetFileDataResponse GetFileData(GetFileDataSOAPService.GetFileDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData", ReplyAction="*")]
        System.Threading.Tasks.Task<GetFileDataSOAPService.GetFileDataResponse> GetFileDataAsync(GetFileDataSOAPService.GetFileDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLatestArchiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLatestArchive", Namespace="http://tempuri.org/", Order=0)]
        public GetFileDataSOAPService.GetLatestArchiveRequestBody Body;
        
        public GetLatestArchiveRequest()
        {
        }
        
        public GetLatestArchiveRequest(GetFileDataSOAPService.GetLatestArchiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLatestArchiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetLatestArchiveRequestBody()
        {
        }
        
        public GetLatestArchiveRequestBody(string filename)
        {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLatestArchiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLatestArchiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetFileDataSOAPService.GetLatestArchiveResponseBody Body;
        
        public GetLatestArchiveResponse()
        {
        }
        
        public GetLatestArchiveResponse(GetFileDataSOAPService.GetLatestArchiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLatestArchiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GetFileDataSOAPService.VEArchive GetLatestArchiveResult;
        
        public GetLatestArchiveResponseBody()
        {
        }
        
        public GetLatestArchiveResponseBody(GetFileDataSOAPService.VEArchive GetLatestArchiveResult)
        {
            this.GetLatestArchiveResult = GetLatestArchiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFirstArchiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFirstArchive", Namespace="http://tempuri.org/", Order=0)]
        public GetFileDataSOAPService.GetFirstArchiveRequestBody Body;
        
        public GetFirstArchiveRequest()
        {
        }
        
        public GetFirstArchiveRequest(GetFileDataSOAPService.GetFirstArchiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFirstArchiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetFirstArchiveRequestBody()
        {
        }
        
        public GetFirstArchiveRequestBody(string filename)
        {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFirstArchiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFirstArchiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetFileDataSOAPService.GetFirstArchiveResponseBody Body;
        
        public GetFirstArchiveResponse()
        {
        }
        
        public GetFirstArchiveResponse(GetFileDataSOAPService.GetFirstArchiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFirstArchiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GetFileDataSOAPService.VEArchive GetFirstArchiveResult;
        
        public GetFirstArchiveResponseBody()
        {
        }
        
        public GetFirstArchiveResponseBody(GetFileDataSOAPService.VEArchive GetFirstArchiveResult)
        {
            this.GetFirstArchiveResult = GetFirstArchiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllArchiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllArchive", Namespace="http://tempuri.org/", Order=0)]
        public GetFileDataSOAPService.GetAllArchiveRequestBody Body;
        
        public GetAllArchiveRequest()
        {
        }
        
        public GetAllArchiveRequest(GetFileDataSOAPService.GetAllArchiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllArchiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetAllArchiveRequestBody()
        {
        }
        
        public GetAllArchiveRequestBody(string filename)
        {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllArchiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllArchiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetFileDataSOAPService.GetAllArchiveResponseBody Body;
        
        public GetAllArchiveResponse()
        {
        }
        
        public GetAllArchiveResponse(GetFileDataSOAPService.GetAllArchiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllArchiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GetFileDataSOAPService.VEArchive[] GetAllArchiveResult;
        
        public GetAllArchiveResponseBody()
        {
        }
        
        public GetAllArchiveResponseBody(GetFileDataSOAPService.VEArchive[] GetAllArchiveResult)
        {
            this.GetAllArchiveResult = GetAllArchiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData", Namespace="http://tempuri.org/", Order=0)]
        public GetFileDataSOAPService.GetFileDataRequestBody Body;
        
        public GetFileDataRequest()
        {
        }
        
        public GetFileDataRequest(GetFileDataSOAPService.GetFileDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetFileDataRequestBody()
        {
        }
        
        public GetFileDataRequestBody(string filename)
        {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetFileDataSOAPService.GetFileDataResponseBody Body;
        
        public GetFileDataResponse()
        {
        }
        
        public GetFileDataResponse(GetFileDataSOAPService.GetFileDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GetFileDataSOAPService.VEDocument GetFileDataResult;
        
        public GetFileDataResponseBody()
        {
        }
        
        public GetFileDataResponseBody(GetFileDataSOAPService.VEDocument GetFileDataResult)
        {
            this.GetFileDataResult = GetFileDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface Service1SoapChannel : GetFileDataSOAPService.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<GetFileDataSOAPService.Service1Soap>, GetFileDataSOAPService.Service1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetFileDataSOAPService.GetLatestArchiveResponse GetFileDataSOAPService.Service1Soap.GetLatestArchive(GetFileDataSOAPService.GetLatestArchiveRequest request)
        {
            return base.Channel.GetLatestArchive(request);
        }
        
        public GetFileDataSOAPService.VEArchive GetLatestArchive(string filename)
        {
            GetFileDataSOAPService.GetLatestArchiveRequest inValue = new GetFileDataSOAPService.GetLatestArchiveRequest();
            inValue.Body = new GetFileDataSOAPService.GetLatestArchiveRequestBody();
            inValue.Body.filename = filename;
            GetFileDataSOAPService.GetLatestArchiveResponse retVal = ((GetFileDataSOAPService.Service1Soap)(this)).GetLatestArchive(inValue);
            return retVal.Body.GetLatestArchiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetFileDataSOAPService.GetLatestArchiveResponse> GetFileDataSOAPService.Service1Soap.GetLatestArchiveAsync(GetFileDataSOAPService.GetLatestArchiveRequest request)
        {
            return base.Channel.GetLatestArchiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetFileDataSOAPService.GetLatestArchiveResponse> GetLatestArchiveAsync(string filename)
        {
            GetFileDataSOAPService.GetLatestArchiveRequest inValue = new GetFileDataSOAPService.GetLatestArchiveRequest();
            inValue.Body = new GetFileDataSOAPService.GetLatestArchiveRequestBody();
            inValue.Body.filename = filename;
            return ((GetFileDataSOAPService.Service1Soap)(this)).GetLatestArchiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetFileDataSOAPService.GetFirstArchiveResponse GetFileDataSOAPService.Service1Soap.GetFirstArchive(GetFileDataSOAPService.GetFirstArchiveRequest request)
        {
            return base.Channel.GetFirstArchive(request);
        }
        
        public GetFileDataSOAPService.VEArchive GetFirstArchive(string filename)
        {
            GetFileDataSOAPService.GetFirstArchiveRequest inValue = new GetFileDataSOAPService.GetFirstArchiveRequest();
            inValue.Body = new GetFileDataSOAPService.GetFirstArchiveRequestBody();
            inValue.Body.filename = filename;
            GetFileDataSOAPService.GetFirstArchiveResponse retVal = ((GetFileDataSOAPService.Service1Soap)(this)).GetFirstArchive(inValue);
            return retVal.Body.GetFirstArchiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetFileDataSOAPService.GetFirstArchiveResponse> GetFileDataSOAPService.Service1Soap.GetFirstArchiveAsync(GetFileDataSOAPService.GetFirstArchiveRequest request)
        {
            return base.Channel.GetFirstArchiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetFileDataSOAPService.GetFirstArchiveResponse> GetFirstArchiveAsync(string filename)
        {
            GetFileDataSOAPService.GetFirstArchiveRequest inValue = new GetFileDataSOAPService.GetFirstArchiveRequest();
            inValue.Body = new GetFileDataSOAPService.GetFirstArchiveRequestBody();
            inValue.Body.filename = filename;
            return ((GetFileDataSOAPService.Service1Soap)(this)).GetFirstArchiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetFileDataSOAPService.GetAllArchiveResponse GetFileDataSOAPService.Service1Soap.GetAllArchive(GetFileDataSOAPService.GetAllArchiveRequest request)
        {
            return base.Channel.GetAllArchive(request);
        }
        
        public GetFileDataSOAPService.VEArchive[] GetAllArchive(string filename)
        {
            GetFileDataSOAPService.GetAllArchiveRequest inValue = new GetFileDataSOAPService.GetAllArchiveRequest();
            inValue.Body = new GetFileDataSOAPService.GetAllArchiveRequestBody();
            inValue.Body.filename = filename;
            GetFileDataSOAPService.GetAllArchiveResponse retVal = ((GetFileDataSOAPService.Service1Soap)(this)).GetAllArchive(inValue);
            return retVal.Body.GetAllArchiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetFileDataSOAPService.GetAllArchiveResponse> GetFileDataSOAPService.Service1Soap.GetAllArchiveAsync(GetFileDataSOAPService.GetAllArchiveRequest request)
        {
            return base.Channel.GetAllArchiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetFileDataSOAPService.GetAllArchiveResponse> GetAllArchiveAsync(string filename)
        {
            GetFileDataSOAPService.GetAllArchiveRequest inValue = new GetFileDataSOAPService.GetAllArchiveRequest();
            inValue.Body = new GetFileDataSOAPService.GetAllArchiveRequestBody();
            inValue.Body.filename = filename;
            return ((GetFileDataSOAPService.Service1Soap)(this)).GetAllArchiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetFileDataSOAPService.GetFileDataResponse GetFileDataSOAPService.Service1Soap.GetFileData(GetFileDataSOAPService.GetFileDataRequest request)
        {
            return base.Channel.GetFileData(request);
        }
        
        public GetFileDataSOAPService.VEDocument GetFileData(string filename)
        {
            GetFileDataSOAPService.GetFileDataRequest inValue = new GetFileDataSOAPService.GetFileDataRequest();
            inValue.Body = new GetFileDataSOAPService.GetFileDataRequestBody();
            inValue.Body.filename = filename;
            GetFileDataSOAPService.GetFileDataResponse retVal = ((GetFileDataSOAPService.Service1Soap)(this)).GetFileData(inValue);
            return retVal.Body.GetFileDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetFileDataSOAPService.GetFileDataResponse> GetFileDataSOAPService.Service1Soap.GetFileDataAsync(GetFileDataSOAPService.GetFileDataRequest request)
        {
            return base.Channel.GetFileDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetFileDataSOAPService.GetFileDataResponse> GetFileDataAsync(string filename)
        {
            GetFileDataSOAPService.GetFileDataRequest inValue = new GetFileDataSOAPService.GetFileDataRequest();
            inValue.Body = new GetFileDataSOAPService.GetFileDataRequestBody();
            inValue.Body.filename = filename;
            return ((GetFileDataSOAPService.Service1Soap)(this)).GetFileDataAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.134:1923/ArchiveManagement.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.134:1923/ArchiveManagement.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
}
